name: Docker Image CI

on:
  push:
    paths: 
    - 'linterbox/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env: 
       DOCKERHUBTOKEN: ${{ secrets.DOCKERHUB }}
      run: |
        echo "$DOCKERHUBTOKEN" | docker login --username friedenberg --password-stdin 
        docker build linterbox/ --file linterbox/Dockerfile --tag friedenberg/linterbox
        docker push friedenberg/linterbox
