name: Docker Image CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env: 
       DOCKERHUBTOKEN: ${{ secrets.DOCKERHUB }}
      run: |
        echo "$DOCKERHUBTOKEN" | docker login --username friedenberg --password-stdin 
        docker build parallel/ --file parallel/Dockerfile --tag friedenberg/parallel
        docker push friedenberg/parallel
