name: Build and Push Parallel Docker Container

on:
  push:
    paths: 
      - "parallel/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
      - name: Build Container
        run:  docker build parallel/ --file parallel/Dockerfile --tag friedenberg/parallel
      - name: Push Container
        env: 
          DOCKERHUBTOKEN: ${{ secrets.DOCKERHUB }}
        run: |
           echo "$DOCKERHUBTOKEN" | docker login --username friedenberg --password-stdin 
           docker push friedenberg/parallel
