name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env: 
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login docker.pkg.github.com -u sfriedenberg -p "$GITHUB_TOKEN"
        docker build shellcheck/ --file shellcheck/Dockerfile --tag docker.pkg.github.com/friedenberg/gcb-builders/shellcheck
        docker push docker.pkg.github.com/friedenberg/gcb-builders/shellcheck
