name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env: 
       DOCKERHUBTOKEN: ${{ secrets.DOCKERHUB }}
      run: |
        echo "$DOCKERHUB" | docker login --username sashafriedenberg --password-stdin 
        docker build shellcheck/ --file shellcheck/Dockerfile --tag sashafriedenberg/gcb-builders/shellcheck
        docker push sashafriedenberg/gcb-builders/shellcheck
